[General]
background=
mainFont=Noto Sans
clockFont=Noto Sans
dateFont=Space Grotesk
mainFontFile=
clockFontFile=
dateFontFile=
iconFontFile=
batteryCapacityFile=
batteryStatusFile=
clockSize=91
clockWeight=350
clockWidth=100
clockRoundness=0
clockVertical=false
showDate=true
showLockedText=true
timeFormat=hh:mm
dateFormat=dddd, d MMMM yyyy
blurEnabled=true
blurRadius=100
wallpaperZoom=1.07
blurZoom=1.1
materialShapeChars=true
contentOpacity=0.1
backgroundOpacity=0.9
extraBackgroundTint=true
surface=#151311
surface_container=#221f1d
surface_container_low=#1e1b19
on_background=#e8e1dd
on_surface=#e8e1dd
on_surface_variant=#cbc5c1
primary=#d9c3ab
on_primary=#3b2e1d
secondary_container=#4f4539
on_secondary_container=#f0e0d0
outline=#95908c
error=#ffb4ab
